### PR TITLE
Filter out staffOnly notes

### LINKED ISSUE #976: Suppress staff-only notes from the indexer
E.g. https://searchworks-folio-dev.stanford.edu/view/5340361 has a note that's marked as `staffOnly`:

```
      {
        "note": "Stanford Auxiliary Library, SAL3 copy 1 (PAGE-SP): The Nelson and Beverly Nagai collection of Asian-American history and culture, circa 1968-1980",
        "staffOnly": true,
        "instanceNoteTypeId": "265c4910-3997-4242-9269-6a4a2e91392b"
      },
```

We shouldn't include any of the staffOnly notes in the index. We're not using them for anything actionable, so it might be OK to change the FOLIO postgres query to remove them or suppress them in the FolioRecord object.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #976

### CODE REVIEW

**Comment by cbeer** [comment]
Don't items and holdings also have notes?

**Comment by jcoyne** [comment]
@cbeer they do, but I haven't yet found examples to test against.

**Comment by jcoyne** [comment]
```
okapi=# SELECT id FROM holdings_record WHERE  jsonb_path_exists(jsonb->'notes', '$ ? (@.staffOnly == true)') limit 10;
                  id
--------------------------------------
 7b3ca732-aac3-417d-9a37-2ab4f35f0d71
 b3115cd7-2735-50d6-b2bc-e6f4e799130f
 889e582e-d0dc-5c1d-aaa6-9d0494fb84ad
 41735750-3700-5d77-a6d0-84fc2d06c000
 7b64f5a9-f9be-5bef-a48d-92a005381af2
 ae35b103-326d-582d-8b4a-0897ff9904e5
 a064d2a3-cdf4-5778-9f65-7fbb1b0afd48
 cdcf0a9d-4171-522b-be69-ce547007737d
 7e14a2ba-0274-58be-892a-7088109e9cdb
 3fe0e4be-862b-5011-abbb-43ee0767a9d9
(10 rows)
```

**Comment by jcoyne** [comment]
This instance has an "staffOnly" item note ("tf:EAST-ASIA 07/28/22 batch"), but that doesn't show up currently https://searchworks-folio-dev.stanford.edu/view/4214746, so I don't think we need to change any behavior for item note. 

This instance has a "staffOnly" holding note ("visib 100 percent as of 2016-05"), but it doesn't show up in searchworks: https://searchworks-folio-dev.stanford.edu/view/L337191

**Pull request merged**
