### PR TITLE
Remove unused title_uniform_display field

### PR DESCRIPTION
**Pull request by marlo-longley**
See https://github.com/sul-dlss/searchworks_traject_indexer/blob/cdad30e01b4e44880af5c68923464adad8a74e2e/lib/traject/config/folio_config.rb#L286

Also, this PR in SearchWorks: https://github.com/sul-dlss/SearchWorks/pull/3870

### CODE REVIEW

**Comment by cbeer** [comment]
Isn't this used in e.g. [13553090](https://searchworks.stanford.edu/view/13553090)?

**Comment by marlo-longley** [comment]
I'm only seeing references to `uniform_title_display_struct` in SW? I am missing something. 
https://github.com/sul-dlss/SearchWorks/blob/8b9a68bf92a7498d2e348c8a1ae3b97a95d7ce87/app/helpers/marc_helper.rb#L10

**Comment by jcoyne** [comment]
@marlo-longley https://github.com/sul-dlss/SearchWorks/blob/066fe7994bf359cbcc7f28e64c5d28dae078665f/app/controllers/catalog_controller.rb#L217

**Comment by marlo-longley** [comment]
@jcoyne see comment on this SearchWorks PR: https://github.com/sul-dlss/SearchWorks/pull/3870#issuecomment-1932730358

I believe we can rely on `uniform_title_display_struct` and go ahead with removing these fields.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
