### PR TITLE
Reenable zeitwerk

### LINKED ISSUE #1187: Restore Zeitwerk
Now that we're all done with jruby.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #1187

### CODE REVIEW

**Review by corylown — COMMENTED** [review]
It looks like the various reader classes don't have access to active_support. Specifically what I'm seeing is when using the `Traject::FolioPostgresReader.find_by_catkey()` from the console I get an `undefined method 'index_by' for` error and `index_by` comes from `active_support/core_ext/enumerable`.

**Comment by jcoyne** [comment]
@corylown I'm unable to duplicate that problem. Can you give me directions so that I can duplicate what you've done to get that error?

**Comment by corylown** [comment]
@jcoyne 

To duplicate the issue:
tunnel to the folio test DB through the indexer-stage server
```
searchworks_traject_indexer % bin/console
irb(main):001> Traject::FolioPostgresReader.find_by_catkey('a1506794', 'postgres.url' => 'pos
tgresql://USER:PASSWORD@localhost:5432/okapi')
searchworks_traject_indexer/lib/traject/readers/folio_postgres_reader.rb:83:in `locations': undefined method `index_by' for...
```

**Comment by jcoyne** [comment]
@corylown Thanks Cory. I believe that is resolved.

**Comment by corylown** [comment]
@jcoyne Yes, it looks like the active_support issue is resolved.

It's not able to load the translation maps:

```
% bundle exec traject -c lib/traject/config/folio_config.rb ./a12451243.json -w --debug-mode
/Users/corylown/.gem/ruby/3.2.2/gems/traject-3.8.1/lib/traject/translation_map.rb:177:in `initialize': No translation map definition file found at 'translation_maps/location_map.[rb|yaml|properties]' in load path:
...
(Traject::TranslationMap::NotFound)
	from lib/traject/config/folio_config.rb:1711:in `new'
	from lib/traject/config/folio_config.rb:1711:in `block in load_config_file'
```

**Comment by jcoyne** [comment]
@corylown that is now resolved.

**Review by corylown — APPROVED** [review]

**Pull request merged**
